//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DistEvent.proto
namespace DistributedTaskCal.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DistCalendarEvent")]
  public partial class DistCalendarEvent : global::ProtoBuf.IExtensible
  {
    public DistCalendarEvent() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _title;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private long _date;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"date", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long date
    {
      get { return _date; }
      set { _date = value; }
    }
    private string _start_time = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private string _end_time = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private string _location = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string location
    {
      get { return _location; }
      set { _location = value; }
    }
    private bool _allday = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"allday", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool allday
    {
      get { return _allday; }
      set { _allday = value; }
    }
    private DistCalendarEvent.EventType _type;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DistCalendarEvent.EventType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EventType")]
    public enum EventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORMAL", Value=0)]
      NORMAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIRTHDAY", Value=1)]
      BIRTHDAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEETING", Value=2)]
      MEETING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PUBLIC_HOLIDAY", Value=3)]
      PUBLIC_HOLIDAY = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}